export const fallbackHeroSlides = [
  {
    id: 'audio',
    badge: 'Featured launch',
    eyebrow: 'Ecovani Store',
    title: 'Immersive audio gear for work, travel, and everyday focus.',
    description:
      'Shop premium headphones, compact speakers, and creator-ready accessories in one polished storefront experience.',
    ctaLabel: 'Shop audio',
    secondaryCtaLabel: 'Customer login',
    panelTitle: 'Nova X Headphones',
    panelDescription: 'Adaptive sound, 32h battery, and a travel-ready foldable build.',
    panelPrice: '$189',
    panelTag: 'Best seller',
    accent: 'from-sky-300 via-cyan-200 to-blue-50',
    image: '/default-hero-banner.svg',
  },
  {
    id: 'workspace',
    badge: 'Workspace picks',
    eyebrow: 'Desk Essentials',
    title: 'Build a cleaner desk setup with smart lighting and compact tech.',
    description:
      'Upgrade your workspace with monitor lights, charging docks, and small devices that remove clutter without losing style.',
    ctaLabel: 'Explore setup',
    secondaryCtaLabel: 'See trending',
    panelTitle: 'ArcView Monitor Lamp',
    panelDescription: 'Glare-free lighting with warm and cool scenes for late-night focus.',
    panelPrice: '$96',
    panelTag: 'Editor choice',
    accent: 'from-slate-200 via-sky-100 to-cyan-50',
    image: '/default-hero-banner.svg',
  },
  {
    id: 'travel',
    badge: 'Travel friendly',
    eyebrow: 'Accessories',
    title: 'Carry smarter with compact accessories made for daily movement.',
    description:
      'From sleeves and pouches to portable charging gear, discover products that make your setup easier to pack and protect.',
    ctaLabel: 'Browse accessories',
    secondaryCtaLabel: 'Open account',
    panelTitle: 'Luma Carry Pouch',
    panelDescription: 'A soft-shell organizer for chargers, cables, and quick-grab travel gear.',
    panelPrice: '$26',
    panelTag: 'New arrival',
    accent: 'from-teal-200 via-cyan-100 to-slate-50',
    image: '/default-hero-banner.svg',
  },
]

export const fallbackCategories = [
  {
    id: 'electronics',
    title: 'Electronics',
    description: 'Smart devices and home tech picked for everyday performance.',
    itemCount: '64 items',
  },
  {
    id: 'accessories',
    title: 'Accessories',
    description: 'Portable add-ons that keep your setup polished and practical.',
    itemCount: '38 items',
  },
  {
    id: 'trending',
    title: 'Trending now',
    description: 'Best-selling essentials customers are adding to cart this week.',
    itemCount: '22 items',
  },
]

export const fallbackProductCollections = [
  {
    id: 'electronics',
    eyebrow: 'Electronics',
    title: 'Smart upgrades for home and work',
    description:
      'Performance-first picks built to streamline your desk, studio, and commute.',
    products: [
      {
        id: 1,
        name: 'Nova X Wireless Headphones',
        category: 'Audio',
        price: '$189',
        originalPrice: '$229',
        rating: '4.8',
        accent: 'from-sky-400 via-cyan-300 to-teal-200',
      },
      {
        id: 2,
        name: 'Pulse Mini Smart Speaker',
        category: 'Home Tech',
        price: '$129',
        originalPrice: '$149',
        rating: '4.7',
        accent: 'from-slate-300 via-sky-200 to-cyan-100',
      },
      {
        id: 3,
        name: 'ArcView 4K Monitor Lamp',
        category: 'Workspace',
        price: '$96',
        originalPrice: '$118',
        rating: '4.9',
        accent: 'from-zinc-200 via-slate-100 to-stone-50',
      },
      {
        id: 4,
        name: 'SwiftCharge Dock Pro',
        category: 'Charging',
        price: '$74',
        originalPrice: '$89',
        rating: '4.6',
        accent: 'from-teal-300 via-cyan-200 to-blue-100',
      },
    ],
  },
  {
    id: 'accessories',
    eyebrow: 'Accessories',
    title: 'Finishing touches that travel well',
    description:
      'Compact, premium add-ons that make your devices easier to carry and enjoy.',
    products: [
      {
        id: 5,
        name: 'Terra Sleeve 14',
        category: 'Laptop Case',
        price: '$42',
        originalPrice: '$54',
        rating: '4.7',
        accent: 'from-sky-200 via-indigo-100 to-slate-50',
      },
      {
        id: 6,
        name: 'Halo MagSafe Wallet',
        category: 'Phone Gear',
        price: '$31',
        originalPrice: '$39',
        rating: '4.5',
        accent: 'from-cyan-200 via-blue-100 to-slate-50',
      },
      {
        id: 7,
        name: 'Orbit Cable Organizer',
        category: 'Desk Setup',
        price: '$18',
        originalPrice: '$24',
        rating: '4.8',
        accent: 'from-teal-200 via-cyan-100 to-blue-50',
      },
      {
        id: 8,
        name: 'Luma Carry Pouch',
        category: 'Travel',
        price: '$26',
        originalPrice: '$34',
        rating: '4.6',
        accent: 'from-slate-200 via-zinc-100 to-stone-50',
      },
    ],
  },
  {
    id: 'trending',
    eyebrow: 'Trending Products',
    title: 'What shoppers are picking today',
    description:
      'Fresh favorites from across the catalog, updated for a fast-moving storefront.',
    products: [
      {
        id: 9,
        name: 'AeroFit Smartwatch',
        category: 'Wearables',
        price: '$149',
        originalPrice: '$179',
        rating: '4.9',
        accent: 'from-blue-300 via-cyan-200 to-sky-100',
      },
      {
        id: 10,
        name: 'Studio Beam Ring Light',
        category: 'Creator Gear',
        price: '$68',
        originalPrice: '$82',
        rating: '4.7',
        accent: 'from-teal-300 via-cyan-200 to-slate-100',
      },
      {
        id: 11,
        name: 'SnapStand Fold Tripod',
        category: 'Mobile Setup',
        price: '$36',
        originalPrice: '$48',
        rating: '4.6',
        accent: 'from-sky-300 via-blue-200 to-cyan-100',
      },
      {
        id: 12,
        name: 'CloudMesh Router Air',
        category: 'Networking',
        price: '$119',
        originalPrice: '$146',
        rating: '4.8',
        accent: 'from-cyan-300 via-sky-200 to-blue-100',
      },
    ],
  },
]

export const trustPoints = [
  'Free shipping over $80',
  '30-day easy returns',
  'Secure checkout with live support',
]
